# Generated by Django 4.0.4 on 2022-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                (
                    "amount_sent",
                    models.PositiveSmallIntegerField(verbose_name="amount sent"),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        db_index=True,
                        help_text="UTM campaign name matches the email class name.",
                        max_length=255,
                        verbose_name="utm campaign name",
                    ),
                ),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
